name: Jeremy Stewart
description: web developer, dog owner, design lover
meta_description: "Web developer, dog owner, design lover."

markdown: redcarpet
highlighter: pygments

paginate: 10
paginate_path: notes/page:num
baseurl: /
domain_name: 'http://jerstew.com'
google_analytics: 'UA-37792076-1'
disqus: false
disqus_shortname: 'jerstew'

# Details for the RSS feed generator
url:            'http://jerstew.com/notes'
author:         'Jeremy Stewart'
authorTwitter:  'jerstew'

permalink:       /notes/:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
